// Generated by Wrangler on Sat Mar 30 2024 18:41:59 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
  APEX_DOMAIN: 'aproxima.net';
  HOME_HOST: 'home.aproxima.net';
  PROTOCOL: 'https:';
  DB: D1Database;
}
