// Generated by Wrangler on Sun Mar 31 2024 12:29:37 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
  APEX_DOMAIN: 'localhost';
  HOME_HOST: 'localhost:3002';
  PROTOCOL: 'http:';
  DB: D1Database;
}
