name = "auth"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "core-db"
# database_id uuid is not a secret, it is used to identify the database in the D1 infrastructure
database_id = "6ea62149-4309-4920-adf6-047d9b614af8"

[env.production.vars]
APEX_DOMAIN = "aproxima.net"
HOME_HOST = "home.aproxima.net"
PROTOCOL = "https:"

[dev]
port = 8585
local_protocol = "http"