// Generated by Wrangler on Sun Mar 10 2024 14:21:08 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

export {};
declare global {
  const APEX_DOMAIN: 'aproxima.net';
  const PROTOCOL: 'https:';
  const DB: D1Database;
}
