// Generated by Wrangler on Sun Mar 31 2024 12:29:44 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
  APEX_DOMAIN: 'aproxima.net';
  PROTOCOL: 'https:';
  DB: D1Database;
}
