name = "core-api"
compatibility_date = "2023-12-01"

[[d1_databases]]
binding = "DB"
database_name = "core-db"
# database_id uuid is not a secret, it is used to identify the database in the D1 infrastructure
database_id = "6ea62149-4309-4920-adf6-047d9b614af8"

[durable_objects]
bindings = [
  { name = "DEVICE_DATA_FEED", class_name = "DeviceDataFeed" },
]

# Callable durable objects
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DeviceDataFeed"]

[dev]
port = 8787
local_protocol = "http"
