name: core-api deploy
on:
  push:
    paths:
      - core-api/**
    branches: [main]
jobs:
  release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core-api
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install bun
      uses: oven-sh/setup-bun@v1
    - name: Install core-api dependencies
      run: bun install --frozen-lockfile
    - name: Login to Cloudflare
      run: bun wrangler:login
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    - name: Publish Worker Script
      run: bun deploy
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}