name: Premerge checks for ui package
on:
  push:
    paths:
      - packages/ui/**
    branches: [main]
  pull_request:
    paths:
      - packages/ui/**
    branches: [main]
jobs:
  premerge:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/ui/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: TypeScript checks
        run: bun run typecheck
      - name: Lint checks
        run: bun run lint
