name: Premerge checks for workers-utils package
on:
  push:
    paths:
      - packages/workers-utils/**
    branches: [main]
  pull_request:
    paths:
      - packages/workers-utils/**
    branches: [main]
jobs:
  premerge:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/workers-utils/
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run typecheck
      - run: bun run lint
