name: Publish @aproxima/eslint-config
on:
  push:
    branches:
      - main
    paths:
      - 'packages/eslint-config/**'
permissions:
  contents: write
  packages: write
jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
    - name: Install bun
      uses: oven-sh/setup-bun@v1
    - name: Install eslint-config dependencies
      run: bun install --frozen-lockfile
    - name: Ensure there are no issues with running lint
      run: bun run lint
    - name: Publish package
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

