name: Publish @aproxima/eslint-config
on:
  push:
    branches:
      - main
    paths:
      - "packages/eslint-config/**"
permissions:
  contents: write
  packages: write
jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run lint
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
